name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y qt6-base-dev cmake libgtest-dev

      - name: Configure CMake
        run: cmake -B build -DCMAKE_CXX_STANDARD=20

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --verbose
